name: Auto Remove Expired Keys
on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  workflow_dispatch:          # Allows manual trigger from the Actions tab
permissions:
  contents: write  # Required for repository modifications
  issues: write    # If the script interacts with issues
jobs:
  clean_keys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: List repository files  # Debugging step to verify file structure
        run: |
          ls -R
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          pip install PyGithub
      - name: Run expired key cleanup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python popup/github_key_manager.py clean \
            --owner npqz \
            --repo popup \
            --token $GITHUB_TOKEN \
            --path Keys
