name: Auto Remove Expired Keys

on:
  schedule:
    - cron: "0 * * * *"  # runs every hour
  workflow_dispatch:       # lets you run manually from GitHub

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Run key system
        run: python key_system.py
      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git commit -m "Auto remove expired keys" || echo "No changes"
          git push
